using Volo.Abp;

namespace ReplyBackSeparateIdentityServer.EntityFrameworkCore;

public abstract class ReplyBackSeparateIdentityServerEntityFrameworkCoreTestBase : ReplyBackSeparateIdentityServerTestBase<ReplyBackSeparateIdentityServerEntityFrameworkCoreTestModule>
{

}
