namespace ReplyBackSeparateIdentityServer;

public abstract class ReplyBackSeparateIdentityServerApplicationTestBase : ReplyBackSeparateIdentityServerTestBase<ReplyBackSeparateIdentityServerApplicationTestModule>
{

}
