namespace ReplyBackSeparateIdentityServer;

public abstract class ReplyBackSeparateIdentityServerDomainTestBase : ReplyBackSeparateIdentityServerTestBase<ReplyBackSeparateIdentityServerDomainTestModule>
{

}
